# Generated by Django 4.0.6 on 2022-07-26 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DragonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('characteristics', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthdate', models.DateField(verbose_name='birthdate')),
                ('dragon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_dragons.dragontype')),
            ],
        ),
    ]
