# Generated by Django 4.0.6 on 2022-07-27 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopters_name', models.CharField(max_length=50)),
                ('id_number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(99999999)])),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AdoptersCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic_name', models.CharField(max_length=50, unique=True)),
                ('characteristic_description', models.CharField(max_length=500)),
                ('list_of_characteristics', models.ManyToManyField(to='register_adopters.adopter')),
            ],
        ),
    ]
