# Generated by Django 4.0.6 on 2022-07-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_adopters', '0002_alter_adopterscharacteristic_list_of_characteristics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopterscharacteristic',
            name='list_of_characteristics',
        ),
        migrations.AddField(
            model_name='adopter',
            name='list_of_characteristics',
            field=models.ManyToManyField(blank=True, to='register_adopters.adopterscharacteristic'),
        ),
    ]
